### ISSUE TITLE
Can not sync from Azure to my local config.

### ISSUE THREAD

**Issue by quistian** [octodns/octodns-azure#68]

**Comment by ross** [comment]
Looks like there originally was content in the issue body, but it was edited out. That intentional? Should this be closed or still running into problems?

**Comment by quistian** [comment]
This item has been resolved. Thanks.

From: Ross McFarland ***@***.***>
Date: Wednesday, August 30, 2023 at 18:30
To: octodns/octodns-azure ***@***.***>
Cc: Russell Sutherland ***@***.***>, Author ***@***.***>
Subject: Re: [octodns/octodns-azure] Can not sync from Azure to my local config. (Issue #68)

Looks like there originally was content in the issue body, but it was edited out. That intentional? Should this be closed or still running into problems?
