### ISSUE TITLE
Missing dependency msrestazure?

### ISSUE THREAD

**Issue by solvaholic** [octodns/octodns-azure#7]
👋 Hiyo! When I install these requirements:

```text
octodns==0.9.14
octodns_route53==0.0.2
boto3==1.20.26
octodns_azure==0.0.1
```

OctoDNS sync fails here:

```text
Traceback (most recent call last):
59
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/azure/common/credentials.py", line 116, in <module>
60
    from msrestazure.azure_active_directory import (
61
ModuleNotFoundError: No module named 'msrestazure'
```

My Python fu is weak, and I've no idea how or whether **msrestazure** _should_ get installed. Poring over dependencies, I think it'd help to add **msrestazure** to this project's **setup.py**:

```text
root@7f5835949637:/config# pip show msrest msrestazure | grep Require
Requires: certifi, isodate, requests, requests-oauthlib
Required-by: azure-mgmt-dns, azure-mgmt-trafficmanager, msrestazure
Requires: adal, msrest, six
Required-by: 
```

Or to have one of the **azure-mgmt-** packages require **msrestazure** instead of or in addition to **msrest**:

```text
root@7f5835949637:/config# pip show azure-mgmt-dns azure-mgmt-trafficmanager | grep Require
Requires: azure-common, azure-mgmt-core, msrest
Required-by: octodns-azure
Requires: azure-common, azure-mgmt-core, msrest
Required-by: octodns-azure
```

Given that the failed import is in the **azure-common** package I'm inclined to address the error there rather than in this project. I started this issue here for visibility, for OctoDNS users.

If y'all have preferences or guidance how to solve this, I'm happy to make a pull request here or take the issue to a different repository. Please let me know what more or different I can provide :bow:

**Comment by ross** [comment]
Hrm. Looks like `msrest` is getting installed automatically as a dep, but `msrestazure` isn't 😦 

```console
$ python3 -m venv env
...
$ source env/bin/activate
$ pip install octodns azure-mgmt-trafficmanager azure-mgmt-dns azure-identity
...
$ pip freeze | grep msrest
msrest==0.6.21
$
```

You want to PR adding it to setup.py or prefer I do?

This is the 2nd one of these, other was in https://github.com/octodns/octodns-route53/pull/6. Will have to think if there's some way to more fully verify the setup.py than https://github.com/octodns/octodns-azure/blob/2368e2101d289a68cedeb5419b2eeb6d888b5b83/script/cibuild#L28-L29.

**Comment by viranch** [comment]
Looks like the fix should be in azure-common.

**Comment by ross** [comment]
> Looks like the fix should be in azure-common.

Yeah. In reality we should be able to specify

```
'azure-mgmt-dns>=8.0.0',
'azure-mgmt-trafficmanager>=0.51.0',
```

in setup.py and get everything else automatically.

**Comment by solvaholic** [comment]
Thank you for checking on this right away @ross @viranch :bow:

> Looks like the fix should be in azure-common.

🎉 I think we all came to the same conclusions. I raised https://github.com/Azure/azure-sdk-for-python/issues/22732 about it, and will defer to y'all if you see a more direct path to solve.

> You want to PR adding it to setup.py or prefer I do?

If y'all would like to add **msrestazure** in this project's setup.py as a workaround, I'm happy to do that :+1:

Otherwise I'll just work around it by adding to my requirements.txt until it's fixed in **azure-common**.

**Comment by ross** [comment]
> If y'all would like to add **msrestazure** in this project's setup.py as a workaround, I'm happy to do that 👍

It probably makes sense to include it for now with a comment linking to https://github.com/Azure/azure-sdk-for-python/issues/22732 saying it can be removed when that's resolved.
