### ISSUE TITLE
(Throttled) Too many operations are requested

### ISSUE THREAD

**Issue by elidhu** [octodns/octodns-azure#95]
We are building a very large zone, and we semi-consistently get throttled.

I believe the provider should be handling this specific case?

```
  Traceback (most recent call last):
    File "/usr/local/bin/octodns-sync", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/octodns/cmds/sync.py", line 62, in main
      manager.sync(
    File "/usr/local/lib/python3.11/dist-packages/octodns/manager.py", line 769, in sync
      ps, d = future.result()
              ^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
      return self.__get_result()
             ^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
      raise self._exception
    File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
      result = self.fn(*self.args, **self.kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/octodns/manager.py", line 527, in _populate_and_plan
      plan = target.plan(zone, processors=processors)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/octodns/provider/base.py", line 226, in plan
      exists = self.populate(existing, target=True, lenient=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/octodns_azure/__init__.py", line 742, in populate
      for azrecord in self._zone_records(rg, zone_name, top):
    File "/usr/local/lib/python3.11/dist-packages/azure/core/paging.py", line 123, in __next__
      return next(self._page_iterator)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/azure/core/paging.py", line 75, in __next__
      self._response = self._get_next(self.continuation_token)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/azure/mgmt/dns/v2018_05_01/operations/_record_sets_operations.py", line 1106, in get_next
      raise HttpResponseError(response=response, error_format=ARMErrorFormat)
  azure.core.exceptions.HttpResponseError: (Throttled) Too many operations are requested. Current operation is throttled.
  Code: Throttled
  Message: Too many operations are requested. Current operation is throttled.
  ```

**Comment by ross** [comment]
Without more/better information from Azure I'm not sure how the client could do anything useful automatically. If it told it how long to wait or the rate limit that was violated it could potentially try and work with that, but with it just saying things have been throttled that doesn't really provide enough info. 

I found https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling. It looks like something that spans all Azure services and isn't specific to DNS. Based on that it seems like the Azure client libraries would be the right place to implement handling for being throttled and not something specific done in octodns-azure. 

Given that it's per region and not per service I don't know how any one client could really implement anything smarter than a wait and retry since other clients could be competing for the same refilled tokens.

**Comment by elidhu** [comment]
Yeah, from what I could see the SDK should handle this case based on a Retry-After header. I haven't had much luck debugging it as it's hard to make it happen in my test environment because _reasons_.

I guess the solution I'm looking for from the perspective of this provider is to expose more of Retry configuration in the hopes we can make it work. It looks like currently the retries are very short and just meant to handle transient network issues.

https://github.com/octodns/octodns-azure/blob/14af9bf40b8b23321c6946c8996b8c98e136333a/octodns_azure/__init__.py#L643-L646

Do you think we could expose the rest of the parameters?

**Comment by ross** [comment]
There's quite a few options, only reasonable way i could see to do it would be to have a `retry_policy` dict param that gets passed into the object as `**retry_policy` so that all of the options would be available w/o having to duplicate everything.

**Comment by ross** [comment]
Wow, so apparently `RetryPolicy` doesn't accept most of it's config options as kwargs, they have to be set as properties after creating the object as is demonstraited in the examples section https://learn.microsoft.com/en-us/python/api/azure-core/azure.core.pipeline.policies.retrypolicy?view=azure-python#examples.

That means the configuration options currently available aren't actually taking effect.

**Comment by elidhu** [comment]
Oh wow, great find - thank you very much!

What an "interesting" API...
